language: node_js
node_js:
- 7.10.0
- 8.11.3
- 9.11.2
- 10.8.0
deploy:
  provider: npm
  email: jgcorradi@gmail.com
  api_key:
    secure: DXZ/4OsAgUhN6O8EaSt1A9rOgHAm4nxkO5z798neHARLYs2CWx7tEzKR8a6cUxpNfMoOYCdVVp8z/VGAlRQYkLeMtBgRHHcX9rKk33BvdU7ANgFTT28PcVOtNY4wf5iurmXNRHdZO4FyrpvVqeoI1fU7FLW/eBET9QvzTVwKwcUYL1DfzO75mSgyQ4feqRPZaH04TOLcQ4UNte0esgaaI6RVf5WE0c/kA1k/Ykx1yKi39q4BzEVb/63jZm2wp8Z50vOLP7LicQXVB5jUbcZIbRoVDnNCbKw54DPxgZR+MqhbKTIGCNOzuO17d+uF3S6R/UMixMciMHUieaw6nuCYzt1NxFDpE7Owo0Vsvp6Sy8ITN+a2HuSiMb9cPVEMdZ7ixMidthDjZ7QwjGnN81tuKcL3z1a19LNn5sZkFy9or2Wxs0cDhVmg1LLA4fI/AOFZdqi5zDbgCsqfLJBo0MC+6eoxtJvOQSdIbRyQSoLdJXU8JF165GxLNjWixKfAQKYidj5GdvaH65cU4VBsHKeXCDlVViBHCNdI8if5Sq6skz8MbG4S29yJ8AKfmQV76RJ1w1xjniio3FLBx+GpZED2oI5eBxxBjSt9qUN/2Lnk7XdaWv65qQX/8i8Gp4SDvY+7ogVTp7V4aq4H9kM01kklHPrF4DUhFQUizI41X4oU+Wo=
  on:
    tags: true
notifications:
  email: false
