language: node_js
node_js:
- 7.10.0
- 8.11.3
- 9.11.2
- 10.8.0
deploy:
  provider: npm
  email: jgcorradi@gmail.com
  api_key:
    secure: wrVKkjKkZGD7ehowvLadY6hkL8JYHwhcM+dNB0CryVUwML9vg2s8vj4oWaHUM0t3nzMUhGt+NMRoIpvK1y0ilar8CElZDFbTZXnkuL1vqLMPVB2qDWQl4hmeSfQP1BpstRxGl7mTJ/EtqTrtw5VVTYGEoqvJPzmIb7uzgaKnvFpgXhSKVmGYgCmM6xSCJoLywTjxAPnHeLQ3RuuAvLVSSLZmpV5VzaHkv+746ZScwnm/wIe5JPqZz7eciFYTQl/Zs9a6Tx7GC7o9/kWGEJv8Kl7ezwaiwQkui47tjzrMFuTLo0pCmZjDJOa9UW+6tVVkftPzVPQwv9PToW3m1yauOTvxDIuyjRGLRbQ2IJjiC8f2tshQUKCtqvZ54QDMYRYne3+6/0/qoMWXZoS3ncnx+cqb1y1Wld8V3D58QASPmQuiyMta+qkUY7p9nle49uRM6+EqRYGIZnKoNS2P8Tk1FiAyoMiE3gCeCBnOG5xJsDHJ6Od3N4ulDI1dh/ljD28D6GFTZYUpa/1HlPGUjRCx+VywiXKi5rYk6HCX3mlWSzFmA7bqRaK+8476yKYLO8mrsaa590IYdruuEaykNv1/SHwrAp8O9qzlmYB/oGMaNoz6Nw065cAibyv1caWDTZICrTRu3HlOCoz455ELmtXz0W+rRQj8N2raTqQ8BG/W5gA=
  on:
    tags: true
notifications:
  email: false
